# Generated by Django 4.2.5 on 2023-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainee_app', '0003_alter_userinput_trainingduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='EmpID',
            field=models.CharField(max_length=50),
        ),
    ]
